export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
export const LOAD_DOC_PAGE_SUCCESS = 'LOAD_DOC_PAGE_SUCCESS';
export const LOAD_DOCUMENTS_PAGE_SUCCESS = 'LOAD_DOCUMENTS_PAGE_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const LOAD_DOCUMENT_SUCCESS = 'LOAD_DOCUMENT_SUCCESS';
export const LOAD_DOC_SUCCESS = 'LOAD_DOC_SUCCESS';
export const SEARCH_DOCUMENT_SUCCESS = 'SEARCH_DOCUMENT_SUCCESS';
export const SEARCH_DOCUMENT_PAGE_SUCCESS = 'SEARCH_DOCUMENT_PAGE_SUCCESS';
export const LOAD_ROLE_DOCUMENTS_SUCCESS ='LOAD_ROLE_DOCUMENTS_SUCCESS';
export const LOAD_ROLE_DOCUMENTS_PAGE_SUCCESS = 'LOAD_ROLE_DOCUMENTS_PAGE_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USERS_PAGE_SUCCESS = 'LOAD_USERS_PAGE_SUCCESS';
export const SEARCH_USER_PAGE_SUCCESS = 'SEARCH_USER_PAGE_SUCCESS';

export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';
export const LOAD_ROLES_PAGE_SUCCESS = 'LOAD_ROLES_PAGE_SUCCESS';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';

export const FAILURE_MESSAGE = 'FAILURE_MESSAGE';